language: generic
sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      before_install: &brew
        - brew update
        - brew install hidapi
    - os: osx
      osx_image: xcode6.4
      before_install: *brew
    - os: osx
      osx_image: xcode8.2
      before_install: *brew
    - os: linux
      dist: trusty
      env: CXX=g++-5
      addons:
        apt:
          packages:
            - libhidapi-dev
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      env: CXX=g++-6
      addons:
        apt:
          packages:
            - libhidapi-dev
            - g++-6
          sources: *sources
    - os: linux
      dist: trusty
      env: CXX=clang++-3.8
      addons:
        apt:
          packages:
            - libhidapi-dev
            - g++-5
            - clang-3.8
          sources: *sources

script:
  - make -j
#  - make test # TODO add library device-less tests