#ifndef LIBNITROKEY_TEST_COMMAND_IDS_HEADER_H_H
#define LIBNITROKEY_TEST_COMMAND_IDS_HEADER_H_H

#define NKSTORAGE_CMD_START_VALUE 0x20
#define NKSTORAGE_CMD_ENABLE_CRYPTED_PARI (NKSTORAGE_CMD_START_VALUE + 0)
#define NKSTORAGE_CMD_DISABLE_CRYPTED_PARI (NKSTORAGE_CMD_START_VALUE + 1)
#define NKSTORAGE_CMD_ENABLE_HIDDEN_CRYPTED_PARI (NKSTORAGE_CMD_START_VALUE + 2)
#define NKSTORAGE_CMD_DISABLE_HIDDEN_CRYPTED_PARI (NKSTORAGE_CMD_START_VALUE + 3)
#define NKSTORAGE_CMD_ENABLE_FIRMWARE_UPDATE (NKSTORAGE_CMD_START_VALUE + 4)
#define NKSTORAGE_CMD_EXPORT_FIRMWARE_TO_FILE (NKSTORAGE_CMD_START_VALUE + 5)
#define NKSTORAGE_CMD_GENERATE_NEW_KEYS (NKSTORAGE_CMD_START_VALUE + 6)
#define NKSTORAGE_CMD_FILL_SD_CARD_WITH_RANDOM_CHARS (NKSTORAGE_CMD_START_VALUE + 7)

#define NKSTORAGE_CMD_WRITE_STATUS_DATA (NKSTORAGE_CMD_START_VALUE + 8)
#define NKSTORAGE_CMD_ENABLE_READONLY_UNCRYPTED_LUN (NKSTORAGE_CMD_START_VALUE + 9)
#define NKSTORAGE_CMD_ENABLE_READWRITE_UNCRYPTED_LUN (NKSTORAGE_CMD_START_VALUE + 10)

#define NKSTORAGE_CMD_SEND_PASSWORD_MATRIX (NKSTORAGE_CMD_START_VALUE + 11)
#define NKSTORAGE_CMD_SEND_PASSWORD_MATRIX_PINDATA (NKSTORAGE_CMD_START_VALUE + 12)
#define NKSTORAGE_CMD_SEND_PASSWORD_MATRIX_SETUP (NKSTORAGE_CMD_START_VALUE + 13)

#define NKSTORAGE_CMD_GET_DEVICE_STATUS (NKSTORAGE_CMD_START_VALUE + 14)
#define NKSTORAGE_CMD_SEND_DEVICE_STATUS (NKSTORAGE_CMD_START_VALUE + 15)

#define NKSTORAGE_CMD_SEND_HIDDEN_VOLUME_PASSWORD (NKSTORAGE_CMD_START_VALUE + 16)
#define NKSTORAGE_CMD_SEND_HIDDEN_VOLUME_SETUP (NKSTORAGE_CMD_START_VALUE + 17)
#define NKSTORAGE_CMD_SEND_PASSWORD (NKSTORAGE_CMD_START_VALUE + 18)
#define NKSTORAGE_CMD_SEND_NEW_PASSWORD (NKSTORAGE_CMD_START_VALUE + 19)
#define NKSTORAGE_CMD_CLEAR_NEW_SD_CARD_FOUND (NKSTORAGE_CMD_START_VALUE + 20)

#define NKSTORAGE_CMD_SEND_STARTUP (NKSTORAGE_CMD_START_VALUE + 21)
#define NKSTORAGE_CMD_SEND_CLEAR_STICK_KEYS_NOT_INITIATED (NKSTORAGE_CMD_START_VALUE + 22)
#define NKSTORAGE_CMD_SEND_LOCK_STICK_HARDWARE (NKSTORAGE_CMD_START_VALUE + 23)

#define NKSTORAGE_CMD_PRODUCTION_TEST (NKSTORAGE_CMD_START_VALUE + 24)
#define NKSTORAGE_CMD_SEND_DEBUG_DATA (NKSTORAGE_CMD_START_VALUE + 25)

#define NKSTORAGE_CMD_CHANGE_UPDATE_PIN (NKSTORAGE_CMD_START_VALUE + 26)


#endif //LIBNITROKEY_TEST_COMMAND_IDS_HEADER_H_H
